### ISSUE TITLE
Unwanted float type

### ISSUE THREAD

**Issue by ghost** [Prakashdeveloper03/Python-Assignments#2]
https://github.com/Prakashdeveloper03/Python-Assignments/blob/5d3fc03c9abd886d484c309f05f99a9b2e360e15/Functions%20II/08_power.py#L4

The power of two `int` will always be an `int` so instead of using `Union[int, float]` just `int` is enough

**Comment by Prakashdeveloper03** [comment]
if exponential part is negative or both base & exponential are negative then result will be `float` type.
for example, 
- 2<sup>-2</sup> = 0.25
- -2<sup>-2</sup> = -0.25
