### ISSUE TITLE
Typing Issue

### ISSUE THREAD

**Issue by ghost** [Prakashdeveloper03/Python-Assignments#3]
https://github.com/Prakashdeveloper03/Python-Assignments/blob/446b1b8129c49a43c37c4262ec3fc39ef7c5bd5b/Functions%20I/03_sphere.py#L5

Here the type `Tuple[float]` should be given as `Tuple[float, float]`. More info https://docs.python.org/3/library/typing.html#typing.Tuple

**Comment by Prakashdeveloper03** [comment]
Thank you, for detecting this issue @AkhilRobert
